version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "4a0b-b204-77d47594655a"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  # app:
  #   build: .
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DefaultConnection=Server=db;Database=CajaMorelia;User Id=sa;Password=4a0b-b204-77d47594655a;
  #   depends_on:
  #     - db

volumes:
  sqlserver-data: